// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType } from 'typesafe-i18n'
import type { LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'ko'

export type Translation = {
	/**
	 * This terminal is not compatible with the interactive CLI function.
The frontbook example download requires an interactive CLI.

You can still manually download the template
from the GitHub from the link below.
Link: https://git.io/JiYK2
	 */
	'nonInteractiveIncompatible': string
	/**
	 * Please select the frontbook demo you want to clone it.

	 */
	'pleaseSelectTemplate': string
	/**
	 * Shall we create a separate folder and create a template in it?
If you select No, it will be immediately clone to 
the folder where the command was executed.
	 */
	'shouldWeCreateAFolder': string
	/**
	 * Please enter the folder name for the clone.
	 */
	'pleaseInputCloneFolderPath': string
	/**
	 * The template download has been completed.
Path: {path}
	 * @param {string} path
	 */
	'downloadedTemplate': RequiredParams1<'path'>
	/**
	 * The folder is not empty, so clone is not possible with that path.
If you want to clone the path right away,
Please empty all files in the path.
	 */
	'folderIsNotEmpty': string
}

export type TranslationFunctions = {
	/**
	 * This terminal is not compatible with the interactive CLI function.
The frontbook example download requires an interactive CLI.

You can still manually download the template
from the GitHub from the link below.
Link: https://git.io/JiYK2
	 */
	'nonInteractiveIncompatible': () => LocalizedString
	/**
	 * Please select the frontbook demo you want to clone it.

	 */
	'pleaseSelectTemplate': () => LocalizedString
	/**
	 * Shall we create a separate folder and create a template in it?
If you select No, it will be immediately clone to 
the folder where the command was executed.
	 */
	'shouldWeCreateAFolder': () => LocalizedString
	/**
	 * Please enter the folder name for the clone.
	 */
	'pleaseInputCloneFolderPath': () => LocalizedString
	/**
	 * The template download has been completed.
Path: {path}
	 */
	'downloadedTemplate': (arg: { path: string }) => LocalizedString
	/**
	 * The folder is not empty, so clone is not possible with that path.
If you want to clone the path right away,
Please empty all files in the path.
	 */
	'folderIsNotEmpty': () => LocalizedString
}

export type Formatters = {}

type Param<P extends string> = `{${P}}`

type Params1<P1 extends string> =
	`${string}${Param<P1>}${string}`

type RequiredParams1<P1 extends string> =
	| Params1<P1>
